apiVersion: v1
kind: Secret
metadata:
  name: summarizer-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "<your_key_here>"


  # env:
  # - name: OPENAI_API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: summarizer-secrets
  #       key: OPENAI_API_KEY