apiVersion: v1
kind: ConfigMap
metadata:
  name: scalalib-config
data:
  DB_URL: "jdbc:postgresql://postgres:5432/summarydb"
  SUMMARIZER_URL: "http://summarizer:8000/summarize"
---
apiVersion: v1
kind: Secret
metadata:
  name: scalalib-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASS: "mysecret"


# envFrom:
#   - configMapRef:
#       name: scalalib-config
#   - secretRef:
#       name: scalalib-secrets

apiVersion: v1
kind: Secret
metadata:
  name: summarizer-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "<your-openai-api-key>"

# env:
#   - name: OPENAI_API_KEY
#     valueFrom:
#       secretKeyRef:
#         name: summarizer-secrets
#         key: OPENAI_API_KEY